version: "3.4"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    env_file: .env
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    tty: true

  mailhog:
    image: mailhog/mailhog
    env_file: .env
    depends_on:
      - php
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  mysql:
    image: mysql:5.7
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    build: nginx
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      # Projects files
      - ${WEBSITES}:/var/www/html:rw,delegated
      # Websites configuration
      - ./nginx/site-available:/etc/nginx/conf.d/:ro
      # Logs
      - ./nginx/log:/var/log/nginx
    depends_on:
      - php
    tty: true

  php:
    build:
      context: ./php
      target: ${DOCKER_PHP_IMAGE}
    env_file: .env
    volumes:
      # Projects files
      - ${WEBSITES}:/var/www/html:rw,delegated
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
      # Logrotate
      - ./php/logrotate.d:/etc/logrotate.d
    depends_on:
      - mysql
      - redis
      - elasticsearch
    tty: true
    links:
      - mysql
      - redis

  redis:
    image: redis:3.2-alpine
    env_file: .env
    volumes:
      - redis:/data
    tty: true

volumes:
  elasticsearch: {}
  mysql: {}
  redis: {}
