version: "3.4"

services:
  elasticsearch:
    build: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=asrp13bgv2

  mailhog:
    image: mailhog/mailhog
    env_file: .env
    depends_on:
      - php
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  mysql:
    image: mariadb:10.4
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  pgsql:
    image: postgres:11.8
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    env_file: .env

  nginx:
    build: nginx
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      # Projects files
      - ${WEBSITES}:/var/www/html:rw,delegated
      # Websites configuration
      - ./nginx/site-available:/etc/nginx/conf.d/:ro
      # Logs
      - ./nginx/log:/var/log/nginx
    depends_on:
      - php
    tty: true

  php:
    build:
      context: ./php
      target: ${DOCKER_PHP_IMAGE}
    env_file: .env
    volumes:
      # Projects files
      - ${WEBSITES}:/var/www/html:rw,delegated
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
      # Logrotate
      - ./php/logrotate.d:/etc/logrotate.d
    depends_on:
      - pgsql
      - mysql
      - redis
      - elasticsearch
    tty: true
    links:
      - mysql
      - redis

  redis:
    image: redis:3.2-alpine
    env_file: .env
    volumes:
      - redis:/data
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql

  phppgadmin:
    image: dockage/phppgadmin
    ports:
      - 8081:80
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=pgsql

volumes:
  mysql: {}
  postgres: {}
  esdata:
    driver: local
  redis: {}
